# -*- coding: utf-8 -*-
"""final_project_end_to_end.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/heyitzrizki/final-project-ds49-group3/blob/main/final%20notebook/final_project_end_to_end.ipynb

# 0. Connect to GitHub

## 0.1 Import Libraries
"""

!pip install catboost
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

from pprint import pprint

# Feature selection & preprocessing
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import RobustScaler

# Model selection & evaluation
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.metrics import mean_squared_error, r2_score

# Regression models
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import HuberRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

# Save artifacts
import json
import joblib

"""## 0.2 Load Dataset"""

url = 'https://raw.githubusercontent.com/heyitzrizki/final-project-ds49-group3/refs/heads/main/data/dataset.csv'
df = pd.read_csv(url)
df.head()

df.info()

#Change format object to date_time

df['actual_delivery_time'] = pd.to_datetime(df['actual_delivery_time'])
df['created_at'] = pd.to_datetime(df['created_at'])
df['market_id'] = df['market_id'].astype('object')

df.info()

"""# 1. Exploratory Data Analysis

## 1.1 Check Null Values
"""

df.isnull().sum()

# Percentage of missing value for each column
missing_percent = df.isnull().sum()/df.shape[0]*100
missing_percent

# Create new DataFrame for plot
missing_percent = missing_percent[missing_percent > 0].sort_values(ascending=True)
missing_df = pd.DataFrame({'column_name': missing_percent.index, 'missing (%)': missing_percent.values})

# Plot
plt.figure(figsize=(10, 6))
sns.barplot(x='missing (%)', y='column_name', data=missing_df, color='deepskyblue')
plt.title('Percentage of Missing Values by Column')
plt.xlabel('Missing (%)')
plt.ylabel('Column Name')
plt.grid(True, axis='x', linestyle='--', alpha=0.7)
for index, value in enumerate(missing_df['missing (%)']):
    plt.text(
        value + 0.1,
        index,
        f"{value:.2f}%",
        va='center',
        fontsize=10,
        color='black'
    )
plt.tight_layout()
plt.show()

"""## 1.2 Check Duplicate Data"""

df_duplicate = df.copy()

df.duplicated().sum()

"""There are no DUPLICATED DATA

## 1.3 Check Unique Values

### 1.3.1 Check Data Shape
"""

df.shape

"""### 1.3.2 Check Data Type"""

df.dtypes

"""### 1.3.3 Check Data Stats"""

df.describe()

"""1. min of min_item_price is -86? Impossible.
2. min value of total_onshift_partners, total_busy_partners, and total_outstanding_orders are negative? Does not make sense.

# 2. Data Preprocessing

### 2.1. Data Cleaning

#### 2.1.1. Handling the negative values
"""

# Identify the Rows with Any Negative Value
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Filter rows where any numerical column has a negative value
negative_rows = df[(df[numerical_cols] < 0).any(axis=1)]

# Display those rows
negative_rows.head()

# Logic-based invalid value detection
invalid_condition = (
    (df['min_item_price'] < 0) |
    (df['total_onshift_partners'] < 0) |
    (df['total_busy_partners'] < 0) |
    (df['total_outstanding_orders'] < 0)
)

# Drop or replace with NaN
df.loc[invalid_condition, ['min_item_price', 'total_onshift_partners', 'total_busy_partners', 'total_outstanding_orders']] = np.nan

"""#### 2.1.2. Check the distribution"""

df_num = df.select_dtypes(exclude=["object", "datetime64[ns]"])

fig_ = df_num.hist(
    figsize=(16, 20),
    bins=50,
    color="deepskyblue",
    edgecolor="black",
    xlabelsize=8,
    ylabelsize=8
)

df['total_busy_partners'].skew()

"""right skewed

#### 2.1.3. Handling outliers
"""

# Boxplot visualization for each numerical feature
for column in df_num.columns:
  plt.figure(figsize=(10, 6))
  sns.boxplot(x=df_num[column])
  plt.title(f'Boxplot of {column}')
  plt.show()

"""Eksperimen 2 skenario:

1. df_no_outlier_all → semua outlier dibuang (agresif)

2. df_no_outlier_partial → hanya sebagian (top extreme) outlier dibuang (moderat)
"""

df_cleaned = df.copy()

cols_outlier_check = ['total_items', 'subtotal', 'num_distinct_items',
                      'min_item_price', 'max_item_price',
                      'total_onshift_partners', 'total_busy_partners',
                      'total_outstanding_orders']

# Remove all outliers with IQR

def remove_all_outliers_iqr(df, cols):
  for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower) & (df[col] <= upper)]
  return df

# Remove top outliers (1%)
def remove_top_percent_outliers(df, cols, percent=0.01):
    for col in cols:
        threshold = df[col].quantile(1 - percent)
        df = df[df[col] <= threshold]
    return df

# Dataset without outliers
df_no_outlier_all = remove_all_outliers_iqr(df_cleaned.copy(), cols_outlier_check)
df_no_outlier_partial = remove_top_percent_outliers(df_cleaned.copy(), cols_outlier_check, percent = 0.01)

print("Original cleaned:", df_cleaned.shape)
print("No outliers (all):", df_no_outlier_all.shape)
print("Partial outliers removed:", df_no_outlier_partial.shape)

"""#### 2.1.4. Handling missing values"""

print("All outlier removed:")
print(df_no_outlier_all.isnull().sum())

print("\nPartial outlier removed:")
print(df_no_outlier_partial.isnull().sum())

# Drop rows with missing target
df_no_outlier_all = df_no_outlier_all.dropna(subset=['actual_delivery_time'])
df_no_outlier_partial = df_no_outlier_partial.dropna(subset=['actual_delivery_time'])

# Fill 'store_primary_category' missing with 'Other'
df_no_outlier_all['store_primary_category'].fillna('Other', inplace=True)
df_no_outlier_partial['store_primary_category'].fillna('Other', inplace=True)

# Fill 'order_protocol' missing with 'unknown'
df_no_outlier_all['order_protocol'].fillna('Unknown', inplace=True)
df_no_outlier_partial['order_protocol'].fillna('Unknown', inplace=True)

print(df_no_outlier_all.isnull().sum())
print(df_no_outlier_partial.isnull().sum())

"""we are not using market_id for further analysis so we left it unchanged."""

df_no_outlier_all.describe()

df_no_outlier_partial.describe()

"""#### 2.1.5. Feature Engineering

Creating "Delivery Time" column
"""

# For full-outlier-removed dataset
df_no_outlier_all['delivery_time'] = df_no_outlier_all['actual_delivery_time'] - df_no_outlier_all['created_at']

# For partial-outlier-removed dataset
df_no_outlier_partial['delivery_time'] = df_no_outlier_partial['actual_delivery_time'] - df_no_outlier_partial['created_at']

# Full outlier removed actual delivery time
df_no_outlier_all['delivery_time'] = (df_no_outlier_all['actual_delivery_time'] - df_no_outlier_all['created_at']).dt.total_seconds() / 60

# Partial outlier removed delivery time
df_no_outlier_partial['delivery_time'] = (df_no_outlier_partial['actual_delivery_time'] - df_no_outlier_partial['created_at']).dt.total_seconds() / 60

"""New feature item_price_range"""

# For full-outlier-removed dataset
df_no_outlier_all['item_price_range'] = df_no_outlier_all['max_item_price'] - df_no_outlier_all['min_item_price']

# For partial-outlier-removed dataset
df_no_outlier_partial['item_price_range'] = df_no_outlier_partial['max_item_price'] - df_no_outlier_partial['min_item_price']

print("All removed - Negative or zero delivery time:", (df_no_outlier_all['delivery_time'] <= 0).sum())
print("Partial removed - Negative or zero delivery time:", (df_no_outlier_partial['delivery_time'] <= 0).sum())

df_no_outlier_all.head()

df_no_outlier_partial.head()

# Because column of ("Created_at" and "actual_delivery_time") was not used (temporary), they can be dropped

cols_to_drop = ['market_id', 'created_at', 'actual_delivery_time', 'store_id']

df_no_outlier_all.drop(columns=cols_to_drop, inplace=True)
df_no_outlier_partial.drop(columns=cols_to_drop, inplace=True)

df_no_outlier_all.head()

df_no_outlier_partial.dtypes

df_no_outlier_all['max_item_price'] = df_no_outlier_all['max_item_price'].astype('float64')

cols_to_int_all = ['total_onshift_partners', 'total_busy_partners', 'total_outstanding_orders',
                   'delivery_time', 'item_price_range']

df_no_outlier_all[cols_to_int_all] = df_no_outlier_all[cols_to_int_all].astype('int64')
df_no_outlier_all.dtypes

df_no_outlier_partial.head()

df_no_outlier_partial.dtypes

df_no_outlier_partial['max_item_price'] = df_no_outlier_partial['max_item_price'].astype('float64')

cols_to_int = ['total_onshift_partners', 'total_busy_partners', 'total_outstanding_orders',
               'delivery_time', 'item_price_range']

df_no_outlier_partial[cols_to_int] = df_no_outlier_partial[cols_to_int].astype('int64')
df_no_outlier_partial.dtypes

df_no_outlier_all.describe()

df_no_outlier_partial.describe()

"""Average delivery time = 46.35 minutes for df_no_outlier_all and 47.13 for df_no_outlier_partial.

Median delivery time = 42.90 minutes for df_no_outlier_all and 43.70 for df_no_outlier_partial

### 2.2. Correlation Heatmap
"""

# Select only numerical columns for a clearer heatmap
numeric_cols_all = df_no_outlier_all.select_dtypes(include=np.number)
numeric_cols_partial = df_no_outlier_partial.select_dtypes(include=np.number)

# --- Heatmap for All Outliers Removed ---
plt.figure(figsize=(12, 10))
correlation_matrix_all_numeric = numeric_cols_all.corr()
sns.heatmap(
    correlation_matrix_all_numeric,
    annot=True,
    cmap='coolwarm',
    fmt=".2f",
    linewidths=.5
)
plt.title('Correlation Heatmap - Numerical Features (All Outliers Removed)', fontsize=16)
plt.show()


# --- Heatmap for Partial Outliers Removed ---
plt.figure(figsize=(12, 10))
correlation_matrix_partial_numeric = numeric_cols_partial.corr()
sns.heatmap(
    correlation_matrix_partial_numeric,
    annot=True,
    cmap='coolwarm',
    fmt=".2f",
    linewidths=.5
)
plt.title('Correlation Heatmap - Numerical Features (Partial Outliers Removed)', fontsize=16)
plt.show()

"""### 2.3. Exploratory Data Visualization

using df_no_outlier_all
"""

# 1. Distribution of target (subtotal)
plt.figure(figsize=(8, 5))
sns.histplot(df_no_outlier_all['subtotal'], kde=True, color='deepskyblue', bins=50)
plt.title('Distribution of Subtotal (All Outliers Removed)')
plt.xlabel('Subtotal')
plt.ylabel('Count')
plt.show()

# 2. Average delivery_time per store category
plt.figure(figsize=(10, 6))
avg_delivery_all = df_no_outlier_all.groupby('store_primary_category')['delivery_time'].mean().sort_values(ascending=False)
sns.barplot(x=avg_delivery_all, y=avg_delivery_all.index, palette='viridis')
plt.title('Average Delivery Time by Store Category (All Outliers Removed)')
plt.xlabel('Average Delivery Time (minutes)')
plt.ylabel('Store Category')
plt.show()

# 3. Scatter plot of delivery_time vs subtotal
plt.figure(figsize=(8, 5))
sns.scatterplot(
    x='delivery_time', y='subtotal',
    data=df_no_outlier_all,
    alpha=0.5, color='tomato'
)
plt.title('Delivery Time vs Subtotal (All Outliers Removed)')
plt.xlabel('Delivery Time (minutes)')
plt.ylabel('Subtotal')
plt.show()

"""using df_no_outlier_partial"""

# 1. Distribution of target (subtotal)
plt.figure(figsize=(8, 5))
sns.histplot(df_no_outlier_partial['subtotal'], kde=True, color='darkorange', bins=50)
plt.title('Distribution of Subtotal (Partial Outliers Removed)')
plt.xlabel('Subtotal')
plt.ylabel('Count')
plt.show()

# 2. Average delivery_time per store category
plt.figure(figsize=(10, 6))
avg_delivery_partial = df_no_outlier_partial.groupby('store_primary_category')['delivery_time'].mean().sort_values(ascending=False)
sns.barplot(x=avg_delivery_partial, y=avg_delivery_partial.index, palette='magma')
plt.title('Average Delivery Time by Store Category (Partial Outliers Removed)')
plt.xlabel('Average Delivery Time (minutes)')
plt.ylabel('Store Category')
plt.show()

# 3. Scatter plot of delivery_time vs subtotal
plt.figure(figsize=(8, 5))
sns.scatterplot(
    x='delivery_time', y='subtotal',
    data=df_no_outlier_partial,
    alpha=0.5, color='seagreen'
)
plt.title('Delivery Time vs Subtotal (Partial Outliers Removed)')
plt.xlabel('Delivery Time (minutes)')
plt.ylabel('Subtotal')
plt.show()

"""### 2.4. Encoding categorical features (One-Hot)"""

df_no_outlier_all.dtypes

# Function: One-Hot Encode all object dtype columns
def one_hot_encode(df):
    # Identify categorical columns (type: object)
    cat_cols = df.select_dtypes(include='object').columns.tolist()

    # Perform One-Hot Encoding
    df_encoded = pd.get_dummies(df, columns=cat_cols, drop_first=False)

    return df_encoded

# Apply to both datasets
df_no_outlier_all_encoded = one_hot_encode(df_no_outlier_all)
df_no_outlier_partial_encoded = one_hot_encode(df_no_outlier_partial)

# Check: Make sure no object dtype remains
print("Remaining object columns (full outliers removed):", df_no_outlier_all_encoded.select_dtypes(include='object').columns.tolist())
print("Remaining object columns (partial outliers removed):", df_no_outlier_partial_encoded.select_dtypes(include='object').columns.tolist())

df_no_outlier_all_encoded.head()

df_no_outlier_partial_encoded.head()

"""### Final dataset"""

# Commented out IPython magic to ensure Python compatibility.
from getpass import getpass
!git clone https://github.com/heyitzrizki/final-project-ds49-group3.git

# STEP 1: Saving to CSV file
df_no_outlier_all_encoded.to_csv("final-project-ds49-group3/data/df_no_outlier_all_encoded.csv", index=False)
df_no_outlier_partial_encoded.to_csv("final-project-ds49-group3/data/df_no_outlier_partial_encoded.csv", index=False)

# STEP 2: Git Configuration
!git config --global user.email "anwars.rizki@gmail.com"
!git config --global user.name "heyitzrizki"

# STEP 3:
# %cd final-project-ds49-group3

# STEP 4: Adding file and Commit
!git add data/df_no_outlier_all_encoded.csv data/df_no_outlier_partial_encoded.csv
!git commit -m "Add encoded datasets (full and partial outlier removed) for modeling phase"

# STEP 5: getpass
token = getpass('Enter your GitHub Personal Access Token: ')

!git push https://heyitzrizki:{token}@github.com/heyitzrizki/final-project-ds49-group3.git

"""# Load Final Dataset"""

url = 'https://raw.githubusercontent.com/heyitzrizki/final-project-ds49-group3/refs/heads/main/data/df_no_outlier_partial_encoded.csv'
df = pd.read_csv(url)
df.head()

"""# Log Data Skewed

## 3.1 Verify Numerical Columns Skewness
"""

continuous_features = [
    'total_items', 'num_distinct_items',
                      'min_item_price', 'max_item_price',
                      'total_onshift_partners', 'total_busy_partners',
                      'total_outstanding_orders'
]

df_skew_verify = df.loc[:, continuous_features]

skew_ft = []

for i in continuous_features:
    # list of skew for each corresponding feature
    skew_ft.append(abs(df_skew_verify[i].skew()))

df_skewed = pd.DataFrame(
    {
        "Columns": continuous_features,
        "Abs_Skew": skew_ft
    }
)

sk_features = df_skewed[df_skewed["Abs_Skew"] > 0.5]["Columns"].tolist()
print("List of skewed features:\n")
print(sk_features)

# loop over i (features) to calculate Log of surfaces
for i in sk_features:

    df[i] = np.log((df[i]) + 1)

# Log transformation of the target variable "subtotal"
df["subtotal_log"] = np.log1p(df["subtotal"])

# Plot the distribution before and after transformation
fig, axes = plt.subplots(1, 2)
fig.suptitle("Distribution of 'Subtotal' Before and After log-transformation")
fontsize = 16

# before log transformation
p = sns.histplot(
    ax=axes[0],
    x=df["subtotal"],
    kde=True,
    bins=100,
    color="deepskyblue"
)
p.set_xlabel("subtotal", fontsize=fontsize)
p.set_ylabel("Count", fontsize=fontsize)

# after log transformation
q = sns.histplot(
    ax=axes[1],
    x=df["subtotal_log"],
    kde=True,
    bins=100,
    color="darkorange"
)

q.set_xlabel("subtotal_log", fontsize=fontsize)
q.set_ylabel("", fontsize=fontsize)

# Drop the original SalePrice
df.drop(
    columns=["subtotal"],
    inplace=True
)

df.head()

"""# Data Splitting and Standardization

#### 4.1 Splitting the Dataset into Train and Test
"""

y = df["subtotal_log"] #Target
X = df.drop(columns="subtotal_log")
print(X.shape)
print(y.shape)

# Create 150 quantile bins for even distribution
bins = np.linspace(0, len(y), 150)
y_binned = np.digitize(y, bins)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y_binned,
    shuffle=True,
    random_state=42
)

print(f"X_train:{X_train.shape}\ny_train:{y_train.shape}")
print(f"\nX_test:{X_test.shape}\ny_test:{y_test.shape}")

y_test.head()

"""#### 4.2 Data Standarization"""

from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
X_train = pd.DataFrame(scaler.fit_transform(X_train),
                       columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(scaler.transform(X_test),
                      columns=X_test.columns, index=X_test.index)

"""# Modelling"""

# Let's define a function for each metrics
# R²
def rsqr_score(test, pred):
    """Calculate R squared score

    Args:
        test -- test data
        pred -- predicted data

    Returns:
        R squared score
    """
    r2_ = r2_score(test, pred)
    return r2_


# RMSE
def rmse_score(test, pred):
    """Calculate Root Mean Square Error score

    Args:
        test -- test data
        pred -- predicted data

    Returns:
        Root Mean Square Error score
    """
    rmse_ = np.sqrt(mean_squared_error(test, pred))
    return rmse_


# Print the scores
def print_score(test, pred):
    """Print calculated score

    Args:
        test -- test data
        pred -- predicted data

    Returns:
        print the regressor name
        print the R squared score
        print Root Mean Square Error score
    """

    print(f"- Regressor: {regr.__class__.__name__}")
    print(f"R²: {rsqr_score(test, pred)}")
    print(f"RMSE: {rmse_score(test, pred)}\n")

# Define regression models
dtr =  DecisionTreeRegressor()
huber = HuberRegressor(epsilon=1.35)  # robust against outliers
# quantile = QuantileRegressor(quantile=0.5, alpha=0.001, solver='highs')  # median regression
rdf = RandomForestRegressor()
xgboost = XGBRegressor()
lgbm = LGBMRegressor()
catboost = CatBoostRegressor()

# Train models on X_train and y_train
for regr in [dtr, huber, rdf, xgboost, lgbm, catboost]:
    # fit the corresponding model
    regr.fit(X_train, y_train)
    y_pred = regr.predict(X_test)
    # Print the defined metrics above for each classifier
    print_score(y_test, y_pred)

"""#### 5.1. XGBoost"""

from sklearn.model_selection import GridSearchCV

# Define hyperparameters
tuned_parameters = {
    "max_depth": [3],
    "colsample_bytree": [0.3, 0.7],
    "learning_rate": [0.01, 0.05, 0.1],
    "n_estimators": [100, 500]
}

# GridSearch
xgbr_cv = GridSearchCV(
    estimator=XGBRegressor(),
    param_grid=tuned_parameters,
    cv=5,
    n_jobs=-1,
    verbose=1
)

# fit the GridSearch on train set
xgbr_cv.fit(X_train, y_train)

# print best params and the corresponding R²
print(f"Best hyperparameters: {xgbr_cv.best_params_}\n")
print(f"Best R²: {xgbr_cv.best_score_}")

# XGB Regressor with the best hyperparameters
xgbr_mod = XGBRegressor(
    seed=20,
    colsample_bytree=xgbr_cv.best_params_["colsample_bytree"],
    learning_rate=xgbr_cv.best_params_["learning_rate"],
    max_depth=xgbr_cv.best_params_["max_depth"],
    n_estimators=xgbr_cv.best_params_["n_estimators"]
)

# Fit the model on train set
xgbr_mod.fit(X_train, y_train)

# Predict on test set
y_pred = xgbr_mod.predict(X_test)

print(f"- {xgbr_mod.__class__.__name__}")
print(f"R²: {rsqr_score(y_test, y_pred)}")
print(f"RMSE: {rmse_score(y_test, y_pred)}")

# Save the model results into lists
model_list = []
r2_list = []
rmse_list = []

model_list.append(xgbr_mod.__class__.__name__)
r2_list.append(round(rsqr_score(y_test, y_pred), 4))
rmse_list.append(round(rmse_score(y_test, y_pred), 4))

y_test = y_test.to_frame()

# Plot Actual vs. Predicted Revenue per Transaction
actual_price = np.expm1(y_test["subtotal_log"])
predicted_price = np.expm1(y_pred)

plt.figure()
plt.title("Actual vs. Predicted Revenue per Transaction\n (XGBoost)", fontsize=20)
plt.scatter(actual_price, predicted_price,
            color="deepskyblue", marker="o", facecolors="none")
plt.plot([0, 10000], [0, 10000], "darkorange", lw=2)
plt.xlim(0, 10000)
plt.ylim(0, 10000)
plt.xlabel("\nActual Price", fontsize=16)
plt.ylabel("Predicted Price\n", fontsize=16)
plt.show()

"""#### 5.2. Decision Tree Regressor"""

tuned_parameters_dt = {
    "max_depth": [3, 5, 10, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

# GridSearch for Decision Tree
dtr_cv = GridSearchCV(
    estimator=DecisionTreeRegressor(random_state=42),
    param_grid=tuned_parameters_dt,
    cv=5,
    n_jobs=-1,
    verbose=1
)

# Fit GridSearch on train set
dtr_cv.fit(X_train, y_train)

# Print best params and best R²
print(f"Best hyperparameters (Decision Tree): {dtr_cv.best_params_}\n")
print(f"Best R²: {dtr_cv.best_score_}")

# Decision Tree Regressor with best hyperparameters
dtr_mod = DecisionTreeRegressor(
    random_state=42,
    max_depth=dtr_cv.best_params_["max_depth"],
    min_samples_split=dtr_cv.best_params_["min_samples_split"],
    min_samples_leaf=dtr_cv.best_params_["min_samples_leaf"]
)

# Fit the model
dtr_mod.fit(X_train, y_train)

# Predict on test set
y_pred_dtr = dtr_mod.predict(X_test)

# Print R² and RMSE
print(f"- {dtr_mod.__class__.__name__}")
print(f"R²: {rsqr_score(y_test, y_pred_dtr)}")
print(f"RMSE: {rmse_score(y_test, y_pred_dtr)}")

# Save results
model_list.append(dtr_mod.__class__.__name__)
r2_list.append(round(rsqr_score(y_test, y_pred_dtr), 4))
rmse_list.append(round(rmse_score(y_test, y_pred_dtr), 4))

# Plot Actual vs. Predicted Revenue per Transaction
actual_price = np.expm1(y_test["subtotal_log"])
predicted_price = np.expm1(y_pred_dtr)

plt.figure()
plt.title("Actual vs. Predicted Revenue per Transaction\n(Decision Tree)", fontsize=20)
plt.scatter(actual_price, predicted_price,
            color="deepskyblue", marker="o", facecolors="none")
plt.plot([0, 10000], [0, 10000], "darkorange", lw=2)
plt.xlim(0, 10000)
plt.ylim(0, 10000)
plt.xlabel("\nActual Price", fontsize=16)
plt.ylabel("Predicted Price\n", fontsize=16)
plt.show()

"""#### 5.3. Huber Regression"""

from sklearn.linear_model import HuberRegressor
from sklearn.model_selection import GridSearchCV

# Define hyperparameters for HuberRegressor
tuned_parameters_huber = {
    "epsilon": [1.1, 1.35, 1.5],  # controls sensitivity to outliers
    "alpha": [0.0001, 0.001, 0.01]  # regularization term
}

# GridSearch for HuberRegressor
huber_cv = GridSearchCV(
    estimator=HuberRegressor(),
    param_grid=tuned_parameters_huber,
    cv=5,
    n_jobs=-1,
    verbose=1,
    scoring='r2'
)

# Fit GridSearch on train set
huber_cv.fit(X_train, y_train)

# Print best params and best R²
print(f"Best hyperparameters (Huber): {huber_cv.best_params_}\n")
print(f"Best R²: {huber_cv.best_score_}")

# Huber Regressor with best hyperparameters
huber_mod = HuberRegressor(
    epsilon=huber_cv.best_params_["epsilon"],
    alpha=huber_cv.best_params_["alpha"]
)

# Fit the model
huber_mod.fit(X_train, y_train)

# Predict on test set
y_pred_huber = huber_mod.predict(X_test)

# Print R² and RMSE
print(f"- {huber_mod.__class__.__name__}")
print(f"R²: {rsqr_score(y_test, y_pred_huber)}")
print(f"RMSE: {rmse_score(y_test, y_pred_huber)}")

# Save results
model_list.append(huber_mod.__class__.__name__)
r2_list.append(round(rsqr_score(y_test, y_pred_huber), 4))
rmse_list.append(round(rmse_score(y_test, y_pred_huber), 4))

# Plot Actual vs. Predicted Revenue per Transaction
actual_price = np.expm1(y_test["subtotal_log"])
predicted_price = np.expm1(y_pred_huber)

plt.figure()
plt.title("Actual vs. Predicted Revenue per Transaction\n(Huber Regressor)", fontsize=20)
plt.scatter(actual_price, predicted_price,
            color="deepskyblue", marker="o", facecolors="none")
plt.plot([0, 10000], [0, 10000], "darkorange", lw=2)
plt.xlim(0, 10000)
plt.ylim(0, 10000)
plt.xlabel("\nActual Price", fontsize=16)
plt.ylabel("Predicted Price\n", fontsize=16)
plt.show()

"""#### 5.4. Random Forest Regressor"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
import matplotlib.pyplot as plt
import numpy as np

# Hyperparameters
param_dist_rf = {
    "n_estimators": [100, 200],
    "max_depth": [10, None],
    "max_features": ["sqrt"],
    "min_samples_split": [2, 5],
}

# RandomizedSearch
rf_random = RandomizedSearchCV(
    estimator=RandomForestRegressor(random_state=42),
    param_distributions=param_dist_rf,
    n_iter=5,            # hanya 5 kombinasi acak
    cv=3,                # 3-fold cross-validation untuk hemat waktu
    n_jobs=-1,
    verbose=1,
    scoring="r2",
    random_state=42
)

# Fit RandomizedSearch
rf_random.fit(X_train, y_train)

# Print
print(f"Best hyperparameters (Random Forest): {rf_random.best_params_}\n")
print(f"Best R²: {rf_random.best_score_}")

rf_mod = rf_random.best_estimator_

# Prediksi pada test set
y_pred_rf = rf_mod.predict(X_test)

# Evaluasi performa
print(f"- {rf_mod.__class__.__name__}")
print(f"R²: {rsqr_score(y_test, y_pred_rf)}")
print(f"RMSE: {rmse_score(y_test, y_pred_rf)}")

model_list.append(rf_mod.__class__.__name__)
r2_list.append(round(rsqr_score(y_test, y_pred_rf), 4))
rmse_list.append(round(rmse_score(y_test, y_pred_rf), 4))

actual_price = np.expm1(y_test["subtotal_log"])
predicted_price = np.expm1(y_pred_rf)

plt.figure()
plt.title("Actual vs. Predicted Revenue per Transaction\n(Random Forest)", fontsize=18)
plt.scatter(actual_price, predicted_price,
            color="deepskyblue", marker="o", facecolors="none")
plt.plot([0, 10000], [0, 10000], "darkorange", lw=2)
plt.xlim(0, 10000)
plt.ylim(0, 10000)
plt.xlabel("\nActual Price", fontsize=14)
plt.ylabel("Predicted Price\n", fontsize=14)
plt.show()

"""#### 5.5. LightGBM Regressor"""

from lightgbm import LGBMRegressor
from sklearn.model_selection import GridSearchCV
import matplotlib.pyplot as plt
import numpy as np

# Define hyperparameters for LightGBM
tuned_parameters_lgb = {
    "num_leaves": [31, 50, 100],
    "max_depth": [-1, 10, 20],
    "learning_rate": [0.01, 0.05, 0.1],
    "n_estimators": [100, 500]
}

# GridSearchCV
lgb_cv = GridSearchCV(
    estimator=LGBMRegressor(random_state=42),
    param_grid=tuned_parameters_lgb,
    cv=5,
    n_jobs=-1,
    verbose=1,
    scoring="r2"
)

# Fit GridSearch
lgb_cv.fit(X_train, y_train)

# Print best params dan best R²
print(f"Best hyperparameters (LightGBM): {lgb_cv.best_params_}\n")
print(f"Best R²: {lgb_cv.best_score_}")

lgb_mod = LGBMRegressor(
    random_state=42,
    num_leaves=lgb_cv.best_params_["num_leaves"],
    max_depth=lgb_cv.best_params_["max_depth"],
    learning_rate=lgb_cv.best_params_["learning_rate"],
    n_estimators=lgb_cv.best_params_["n_estimators"]
)

# Fit model
lgb_mod.fit(X_train, y_train)

# Predict pada test set
y_pred_lgb = lgb_mod.predict(X_test)

# Print R² dan RMSE
print(f"- {lgb_mod.__class__.__name__}")
print(f"R²: {rsqr_score(y_test, y_pred_lgb)}")
print(f"RMSE: {rmse_score(y_test, y_pred_lgb)}")

model_list.append(lgb_mod.__class__.__name__)
r2_list.append(round(rsqr_score(y_test, y_pred_lgb), 4))
rmse_list.append(round(rmse_score(y_test, y_pred_lgb), 4))

actual_price = np.expm1(y_test["subtotal_log"])
predicted_price = np.expm1(y_pred_lgb)

plt.figure()
plt.title("Actual vs. Predicted Revenue per Transaction\n(LightGBM)", fontsize=18)
plt.scatter(actual_price, predicted_price,
            color="deepskyblue", marker="o", facecolors="none")
plt.plot([0, 10000], [0, 10000], "darkorange", lw=2)
plt.xlim(0, 10000)
plt.ylim(0, 10000)
plt.xlabel("\nActual Price", fontsize=14)
plt.ylabel("Predicted Price\n", fontsize=14)
plt.show()

"""#### 5.6. CatBoost Regressor"""

from catboost import CatBoostRegressor

# Define hyperparameters for CatBoost
tuned_parameters_catboost = {
    "depth": [4, 6, 10],
    "learning_rate": [0.01, 0.05, 0.1],
    "iterations": [100, 500]
}

# GridSearchCV for CatBoost
catboost_cv = GridSearchCV(
    estimator=CatBoostRegressor(verbose=0, random_state=42),
    param_grid=tuned_parameters_catboost,
    cv=5,
    n_jobs=-1,
    verbose=1,
    scoring="r2"
)

# Fit GridSearch
catboost_cv.fit(X_train, y_train)

# Print best parameters and best R²
print(f"Best hyperparameters (CatBoost): {catboost_cv.best_params_}\n")
print(f"Best R²: {catboost_cv.best_score_}")

# CatBoost Regressor with best hyperparameters
catboost_mod = CatBoostRegressor(
    depth=catboost_cv.best_params_["depth"],
    learning_rate=catboost_cv.best_params_["learning_rate"],
    iterations=catboost_cv.best_params_["iterations"],
    verbose=0
)

# Fit model
catboost_mod.fit(X_train, y_train)

# Predict pada test set
y_pred_catboost = catboost_mod.predict(X_test)

# Print R² dan RMSE
print(f"- {catboost_mod.__class__.__name__}")
print(f"R²: {rsqr_score(y_test, y_pred_catboost)}")
print(f"RMSE: {rmse_score(y_test, y_pred_catboost)}")

model_list.append(catboost_mod.__class__.__name__)
r2_list.append(round(rsqr_score(y_test, y_pred_catboost), 4))
rmse_list.append(round(rmse_score(y_test, y_pred_catboost), 4))

actual_price = np.expm1(y_test["subtotal_log"])
predicted_price = np.expm1(y_pred_catboost)

plt.figure()
plt.title("Actual vs. Predicted Revenue per Transaction\n(CatBoost)", fontsize=18)
plt.scatter(actual_price, predicted_price,
            color="deepskyblue", marker="o", facecolors="none")
plt.plot([0, 10000], [0, 10000], "darkorange", lw=2)
plt.xlim(0, 10000)
plt.ylim(0, 10000)
plt.xlabel("\nActual Price", fontsize=14)
plt.ylabel("Predicted Price\n", fontsize=14)
plt.show()

"""#### 5.7. Interpretation of Model Performance"""

# Create a table with pd.DataFrame
model_results = pd.DataFrame(
    {
        "Model": model_list,
        "R²": r2_list,
        "RMSE": rmse_list
    }
)

model_results = model_results.sort_values(by="R²", ascending=False).reset_index(drop=True)
model_results

"""The evaluation results show that LGBMRegressor achieved the highest R² score (0.8117) and the lowest RMSE (0.2743), indicating it explains about 81.1% of the variance in the target variable while having the smallest prediction error among all models tested. CatBoostRegressor and XGBRegressor performed very closely, with R² above 0.809, making them strong alternatives. RandomForestRegressor also delivered good performance but slightly lower accuracy (R² = 0.8002). The DecisionTreeRegressor and HuberRegressor lagged behind, with notably lower R² and higher RMSE, suggesting they are less capable of capturing the underlying patterns in this dataset. Overall, the gradient boosting models (LightGBM, CatBoost, XGBoost) clearly outperform other algorithms in both predictive accuracy and error minimization.

# Deployment
"""

# ==== Save artifacts for Streamlit inference ====
# Why: LGBM model was trained WITH preprocessing (log1p on skewed cols,
# RobustScaler, and a specific feature subset/order). If only save the model,
# predictions in Streamlit will be wrong or crash. We therefore save:
# 1) the trained scaler, 2) the trained model, 3) the exact feature order used,
# 4) which columns were log-transformed during training.

import json
import joblib

# Safety checks to avoid exporting half-baked objects
assert "scaler" in globals(), "scaler not found. Fit RobustScaler before exporting."
assert "lgb_mod" in globals(), "lgb_mod not found. Train your LGBM model first."
assert "X_train" in globals(), "X_train not found. Make sure your final feature set exists."
assert "sk_features" in globals(), "sk_features not found. Compute skewed columns first."

# 1) Save the RobustScaler fitted on TRAIN data
joblib.dump(scaler, "scaler.pkl")

# 2) Save the trained LightGBM model (predicts on *log* target: subtotal_log)
joblib.dump(lgb_mod, "lgbm_model.pkl")

# 3) Save the exact feature order used at training time
#    (after backward stepwise + VIF drops). Inference MUST respect this order.
feature_order = list(X_train.columns)
with open("feature_order.json", "w") as f:
    json.dump(feature_order, f)

# 4) Save which numeric columns were log-transformed (so we can replicate inference)
with open("skewed_cols.json", "w") as f:
    json.dump(list(sk_features), f)

print("Artifacts saved: scaler.pkl, lgbm_model.pkl, feature_order.json, skewed_cols.json")

# Commented out IPython magic to ensure Python compatibility.
import os

# 1) Clone your repo
!git clone https://github.com/heyitzrizki/final-project-ds49-group3.git

# 2) Save artifacts into the repo under deployment/
artifact_dir = "final-project-ds49-group3/deployment"
os.makedirs(artifact_dir, exist_ok=True)

joblib.dump(scaler, os.path.join(artifact_dir, "scaler.pkl"))
joblib.dump(lgb_mod, os.path.join(artifact_dir, "lgbm_model.pkl"))

feature_order = list(X_train.columns)
with open(os.path.join(artifact_dir, "feature_order.json"), "w") as f:
    json.dump(feature_order, f)

# If you DO NOT use skewed feature log-transform at inference, skip this file.
with open(os.path.join(artifact_dir, "skewed_cols.json"), "w") as f:
    json.dump(list(sk_features), f)

# 3) Git config
!git config --global user.email "anwars.rizki@gmail.com"
!git config --global user.name "heyitzrizki"

# 4) Add, commit, push
# %cd final-project-ds49-group3
!git add deployment/scaler.pkl deployment/lgbm_model.pkl deployment/feature_order.json deployment/skewed_cols.json
!git commit -m "Add Streamlit deployment artifacts"
token = getpass("Enter your GitHub Personal Access Token: ")
!git push https://heyitzrizki:{token}@github.com/heyitzrizki/final-project-ds49-group3.git

